### ISSUE TITLE
How i can change the result of headers file

### ISSUE THREAD

**Issue by Omardavinci** [ArachisH/Sulakore#1]
Sorry i was refering to habbit. For mistake i opened the issue in sulakore. The question is how i can put first hash and after header since source code with habbit. Sorry for the issue.
Hi awesome projects man you are  really very smart. Shame that you left tanji project. My question is about how i can change the result of this file. In other words how i can change the order of messages since source code.  Sorry for my stupidity and thx a lot for all your job.

**Comment by ArachisH** [comment]
Re-write this issue in the HabBit repository, with an example of what you want, I'll help you there.
