### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wthks** [ArachisH/Sulakore#15]
Hey there!

Does Sulakore has a documentation or some example files?
I would like to make a farming tool. but I don't know where to start.

I would like to know how I can get the sso ticket or how it would be possible to connect my habbo and then control it.

I found this in another repo.
[Habbo-Bot](https://github.com/MelSoJelly/Habbo-Bot/blob/master/Connection.cs)
and tried it to modify with the latest Sulakore
```cs
var S = await Node.ConnectNewAsync("retro", 30000); //example
if (S)
{
    Debug.WriteLine("Connected");
    await Node.SendAsync(HPacket.ToBytes(HFormat.WedgieOut, "{l}{u:4000}{s:PRODUCTION HERE}{s:FLASH}{i:1}{i:0}"));
    await Node.SendPacketAsync(1961, "[0][0][0][2][7]©");
    var c = await Node.ReceivePacketAsync();
    while (c != null)
    {
        Debug.WriteLine("Incoming packet: " + c.ReadUTF8());
        c = await Node.ReceivePacketAsync();
    }
}
```

**Comment by ghost** [comment]
Examples:
https://github.com/xnumad/Effectz
https://github.com/gabl00n/PosWalker
https://github.com/gabl00n/PleaseNoLag
https://github.com/xAstroBoy/RetroFun

SSO Token API: https://www.habbo.com/api/ssotoken

**Comment by wthks** [comment]
Thanks for the links
Are there examples of retro servers?

I want to connect with the tool and control the User without having habbo open
