### ISSUE TITLE
Node encryption

### ISSUE THREAD

**Issue by PercivallAkihiko** [ArachisH/Sulakore#40]
I'm trying to learn about the SDK by first making an handshake. I managed to exchage keys but after I give to RC4 the key and encrypt the node, the server stops to respond. Instead after a while server just asks for ping  and sends DisconnectReasonEvent.
Sometimes I get packets after the handshake with an unknow id, I've searched them on Sulek but nothing match.

```c#
byte[] key = _keyExchange.GetSharedKey(packet.ReadUTF8());

_hnode.Decrypter = new RC4(key);
_hnode.Encrypter = new RC4(key);
```

**Comment by PaulusParssinen** [comment]
What disconnection reason are you getting? You can try check for corresponding reason identifier in [`HDisconnectReason`](https://github.com/ArachisH/Sulakore/blob/main/Sulakore/Habbo/Enums/HDisconnectReason.cs). The reason should be encoded in the disconnection event.

There could be many things going wrong and I'm not confident about the correctness of HKeyExchange either which does not help 😅 HKeyExchange is currenly also being "rewritten" in https://github.com/ArachisH/Sulakore/pull/34.

Also, I would need to see the entire exchange logic to see if there's something obvious wrong or if it's just HKeyExchange failing.

**Comment by PercivallAkihiko** [comment]
I've checked the reason and it's **PongTimeout**. As I mentioned server doesn't respond to any of my packet after I receive **CompleteDiffieHandshake**, I'm sending **Pong** after server's **Ping**, but I guess that the server does not receive the packet.

The only packet that I manage to exchange are:
```
Out: ClientHello
Out: InitDiffieHandshake
In: InitDiffieHandshake
Out: CompleteDiffieHandshake
In: CompleteDiffieHandshake
```
I'm sending the Id that I get from G-Earth packet logger, could be that a problem? I'll try to use Sulakore's headers if I can. Still trying to figure out how Outcoming.cs/Incoming.cs does work.
How do I know if the shared key is right? If it's wrong does that mean that the server ignores every packet that can't be decoded?

**Comment by PaulusParssinen** [comment]
Solved the main issue with discord discussion. Issue was that the client was connecting to Websocket endpoint instead of the flash one.
